name: Code Style

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  codestyle:
    name: Code Style (fmt + clippy)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Rust
        uses: Swatinem/rust-cache@v1
      - name: Check formatting
        run: cargo fmt --all -- --check
      - name: Check lints (cargo clippy)
        run: cargo clippy -- -D warnings
